INSERT INTO interests (slug, label) VALUES
  ('travel', 'Travel'),
  ('hiking', 'Hiking'),
  ('cooking', 'Cooking'),
  ('coffee', 'Coffee'),
  ('music', 'Music'),
  ('live_music', 'Live music'),
  ('movies', 'Movies'),
  ('reading', 'Reading'),
  ('photography', 'Photography'),
  ('art', 'Art'),
  ('museums', 'Museums'),
  ('fitness', 'Fitness'),
  ('running', 'Running'),
  ('yoga', 'Yoga'),
  ('cycling', 'Cycling'),
  ('swimming', 'Swimming'),
  ('dancing', 'Dancing'),
  ('gaming', 'Gaming'),
  ('board_games', 'Board games'),
  ('gardening', 'Gardening'),
  ('pets', 'Pets'),
  ('foodie', 'Food and dining'),
  ('wine', 'Wine'),
  ('theatre', 'Theatre'),
  ('volunteering', 'Volunteering'),
  ('technology', 'Technology'),
  ('camping', 'Camping'),
  ('beach', 'Beach'),
  ('writing', 'Writing'),
  ('languages', 'Languages')
ON CONFLICT (slug) DO NOTHING;
