-- Reference catalogue of interests (product data, not demo data).
INSERT INTO interests (slug, label) VALUES
  ('travel', 'Voyages'),
  ('hiking', 'Randonnée'),
  ('cooking', 'Cuisine'),
  ('wine', 'Vin'),
  ('coffee', 'Café'),
  ('music', 'Musique'),
  ('concerts', 'Concerts'),
  ('cinema', 'Cinéma'),
  ('series', 'Séries'),
  ('reading', 'Lecture'),
  ('writing', 'Écriture'),
  ('photography', 'Photographie'),
  ('art', 'Art'),
  ('museums', 'Musées'),
  ('theatre', 'Théâtre'),
  ('dance', 'Danse'),
  ('yoga', 'Yoga'),
  ('running', 'Course à pied'),
  ('fitness', 'Sport en salle'),
  ('cycling', 'Vélo'),
  ('swimming', 'Natation'),
  ('climbing', 'Escalade'),
  ('football', 'Football'),
  ('tennis', 'Tennis'),
  ('gaming', 'Jeux vidéo'),
  ('board_games', 'Jeux de société'),
  ('tech', 'Tech'),
  ('nature', 'Nature'),
  ('animals', 'Animaux'),
  ('gardening', 'Jardinage'),
  ('volunteering', 'Bénévolat'),
  ('languages', 'Langues'),
  ('fashion', 'Mode'),
  ('design', 'Design'),
  ('meditation', 'Méditation'),
  ('brunch', 'Brunch')
ON CONFLICT (slug) DO NOTHING;
